---

- name: Copy matlab license
  ansible.builtin.copy:
    src: "{{ LicenseFile }}"
    dest: /tmp/matlab/license.lic
    owner: root
    group: root
    mode: 0644

- name: Customize installer_input.txt
  ansible.builtin.lineinfile:
    dest: "{{ item.dest }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { dest: '/tmp/matlab/installer_input.txt', regexp: '^"# destinationFolder"', line: ' destinationFolder={{ destinationFolder }}/{{ matlab_version }}' }
    - { dest: '/tmp/matlab/installer_input.txt', regexp: '^"# fileInstallationKey"', line: 'fileInstallationKey={{ fileInstallationKey }}' }
    - { dest: '/tmp/matlab/installer_input.txt', regexp: '^"# agreeToLicense"', line: 'agreeToLicense=yes' }
    - { dest: '/tmp/matlab/installer_input.txt', regexp: '^"# outputFile"', line: ' outputFile=/tmp/matlab/mathworks_root.log' }
    - { dest: '/tmp/matlab/installer_input.txt', regexp: '^"# improveMATLAB"', line: 'improveMATLAB=no' }
    - { dest: '/tmp/matlab/installer_input.txt', regexp: '^"# licensePath"', line: 'licensePath=/tmp/matlab/license.lic' }

- name: Start silent Matlab installation
  # noqa 301 Reason: This will never bbe executed when matlab is already installed.
  ansible.builtin.command: "{{ installationFolder }}/install -inputFile /tmp/matlab/installer_input.txt -v "
